beeware/briefcase-linux-system-template

tests/apps/verify-pyside2/pyproject.toml
tests/apps/verify-pyside6/pyproject.toml
tests/apps/verify-toga/pyproject.toml

With the addition of Arch system packages, and the introduction of beeware/.github#171, we need to update the test projects to include all the Arch system requirements. 
There's also been some drift in runtime requirements; these aren't a problem in practice as we don't run the apps, but it's worth adding them anyway for consistency.

Update test project system requirements

---

.gitignore
cookiecutter.json
{{ cookiecutter.format }}/Dockerfile

- Adds support to conditionally introduce a step down user (i.e. "brutus") in images created from the Dockerfile
- This is required for Docker Desktop and rootless Docker as outlined in beeware/briefcase#1083
BRIEFCASE_REPO: https://github.com/rmartin16/briefcase/
BRIEFCASE_REF: docker-desktop

Add support to conditionally step down from root

---

{{ cookiecutter.format }}/Dockerfile

- Since the Briefcase data directory is bind mounted in to the `.cache` directory when `.cache` does not yet exist, Docker assigns `root` as its owner and this can create spurious warnings for applications trying to use `.cache` while building/installing.

Assign `brutus` as owner of `/home/brutus/.cache`

---

tests/apps/verify-pygame/pyproject.toml
tests/apps/verify-toga/pyproject.toml
{{ cookiecutter.format }}/Dockerfile

- Given that a distro provided `pip` may be quite old, install the latest `pip` inside the image
- To accommodate [PEP 668](https://peps.python.org/pep-0668/), the latest `pip` is installed using `PIP_BREAK_SYSTEM_PACKAGES=1`
- Update Toga and Pygame tests so they use the local repo for CI instead of downloading the current one
- Aligned the `pyproject.toml` configs for the test apps with current `briefcase-template`

Install the latest version of `pip`

---

{{ cookiecutter.format }}/Dockerfile

c444448
BRIEFCASE_REPO:  https://github.com/rmartin16/briefcase/
BRIEFCASE_REF: tools-bind-mount

Revert c444448 since Briefcase no longer mounting to `~/.cache`

---

{{ cookiecutter.format }}/Dockerfile

- PEP 668 allows distros to explicitly declare system-installed Python packages as "externally managed" and prevent `pip` from updating them directly instead of through the distro's package manager.
- To accommodate this, `pip` is now installed with `pacman` instead of `ensurepip` and is updated via the [previous implementation](https://github.com/beeware/briefcase-linux-system-template/pull/8) of `PIP_BREAK_SYSTEM_PACKAGES`.
- First discovered in CI for beeware/briefcase#1417

Fix `pip` install for Arch support for PEP 668

---

{{ cookiecutter.format }}/Dockerfile

- If the `SYSTEM_REQUIRES` list is updated long after the image is created, then the attempt to install the new requirements may use an out-dated apt cache and will likely error during the install.
- Ensures `apt-get update` is always run before an apt install.
- The other package managers are more sane and only attempt an install with an up-to-date cache.

Ensure `apt` is always up-to-date before installing

---

{{ cookiecutter.format }}/Dockerfile

Anytime one of the SDL based GUI toolkits tries to connect to audio inside Docker, it's going to fail....so, just disable it inside the container.

Disable SDL from attempting to connect to audio

---

{{ cookiecutter.format }}/Dockerfile

- Install git so pip can install from local directories
- Explicitly include pkg-config
- Remove pwdutils since tumbleweed appears to contain them already
- Despite this [comment](https://github.com/beeware/briefcase-linux-system-template/pull/11#pullrequestreview-1603845755), I cannot find evidence that `opensuse/tumbleweed` doesn't come with the tools to create a user. Were you using a different image possibly?

Update system packages to install in image

---

{{ cookiecutter.format }}/Dockerfile

- Install git so pip can install from local directories
- Explicitly include pkg-config
- Remove pwdutils since tumbleweed appears to contain them already
- Backport of https://github.com/beeware/briefcase-linux-system-template/pull/19

Update system packages to install in image (v0.3.17 backport)

---

{{ cookiecutter.format }}/Dockerfile

In the Dependabot overnights, we started seeing failures because the installation of `rpm-build` was incompatible with the existing install of `busybox-diffutils`. `busybox-diffutils` is installed by the `devel_basis` template.
However if you install `devel_basis` *after* installing `rpm-build`, busybox et al appears to be committed from the installation list.

Change the order of installation for devel-basis under SuSE

---

{{ cookiecutter.format }}/Dockerfile

- Closes https://github.com/beeware/briefcase/issues/1738
- I used `PIP_IGNORE_INSTALLED` instead of `--ignore-installed` just in case the available `pip` is older and `--ignore-installed` might not be available

Ignore any installed packages when installing pip et al

---

{{ cookiecutter.format }}/bootstrap/main.c

The current stub binary used in a packaged system app returns `sys.executable` as `python3`. This is neither correct, nor helpful.
The equivalent change isn't needed on macOS because macOS has special handling that overrides the config setting.

Ensure that sys.executable returns the executable name

---

{{ cookiecutter.format }}/Dockerfile

The recent update to use PIP_BREAK_SYSTEM_PACKAGES appears to have [caused a problem on Arch](https://github.com/beeware/briefcase/actions/runs/8918302073/job/24493177612).
We use PIP_BREAK_SYSTEM_PACKAGES to install setuptools. However, Arch then tries to install `python-setuptools` as a an optional build component of the python package. It then complains because it would need to overwrite existing files.
This change installs python-setuptools as part of the initial Python install, which means that the python install can overwrite the setuptools install, rather than the other way around.

Ensure the system package for setuptools is installed on Arch

---

cookiecutter.json
{{ cookiecutter.format }}/bootstrap/main.c

Add support for `BRIEFCASE_DEBUG`, and by extension, improve support for console apps.
Refs beeware/briefcase#1781

Add support for BRIEFCASE_DEBUG.

---

.github/workflows/ci.yml
cookiecutter.json

- Drop Python 3.8 as Briefcase's `main` branch no longer supports it

Drop Python 3.8 support

---

.pre-commit-config.yaml

Bumps `pre-commit` hook for `pre-commit-hooks` from v4.5.0 to v5.0.0 and ran the update against the repo.

Bump pre-commit-hooks from v4.5.0 to v5.0.0

---

.github/workflows/ci.yml

beeware/.github#172 adds the ability to explicitly declare the use of the system python. 
This adds a test of the system Python to the test matrix. 
The TODO will need to be removed once the upstream PR has been merged.

Include explicit testing for system python.

---

.github/workflows/ci.yml

As with the [Flatpak change](https://github.com/beeware/briefcase-linux-flatpak-template/pull/55), this doubles the number of jobs....but these repos don't see too much traffic....

Run CI on linux/arm64

---

{{ cookiecutter.format }}/bootstrap/main.c

Fixes #34.
Implements the same fix as https://github.com/beeware/briefcase-macOS-Xcode-template/pull/65.

Allow for runpy returning non-integer results.

---

{{ cookiecutter.format }}/bootstrap/main.c

As described [here](https://github.com/beeware/briefcase/issues/2195#issuecomment-2727821874), the `app_packages` should be added via `site.addsitedir()` so that `.pth` files are executed correctly.
I tested it with a minimal example project I made for this: [pth-execution-checker](https://github.com/timrid/pth-execution-checker)
Should fix https://github.com/beeware/briefcase/issues/2195, https://github.com/beeware/briefcase/issues/669 and https://github.com/beeware/briefcase/issues/381 for "linux system".
There are also a similar PRs for:
- "windows visualstudio": https://github.com/beeware/briefcase-windows-VisualStudio-template/pull/52 
- "linux flatpak": https://github.com/beeware/briefcase-linux-flatpak-template/pull/58

Add processing of .pth files from "app_packages".

---

.github/workflows/ci.yml
{{ cookiecutter.format }}/bootstrap/main.c

Python 3.9 is EOL; 3.14 is now available.
Also includes the fix for locale initialization (see beeware/briefcase-iOS-Xcode-template#57).

Drop Python 3.9, add 3.14
